### ISSUE TITLE
Length of the destination address is not checked on frontend

### ISSUE THREAD

**Issue by mertwole** [gear-tech/gear-bridges#222]

**Comment by nikitayutanov** [comment]
For which network, Vara or Ethereum? There are validation checks for both of them.

On Vara we're trying to decode address via keyring, and if decoding is successful - provided address is valid.
Same thing happens for Ethereum, I guess, except there's a ready `isAddress` util.

**Comment by mertwole** [comment]
![image](https://github.com/user-attachments/assets/2396c623-1d83-4f42-8498-35c1d40ee3f3)
![image](https://github.com/user-attachments/assets/df5d2eb3-ba70-431e-b2a5-2a899756cd3a)
But approve will be sent
